name: Run backend tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
      - run: go version

      - name: Tidy packages
        working-directory: ./packages/server
        run: go mod tidy

      - name: Run backend tests
        working-directory: ./packages/server
        run: go test
